In [22]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
data = pd.read_csv(r'..\Datasets\Raw\Food delivery.csv')

In [23]:
data.describe(include='all')

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
count,45593,45593,45593,45593,45593.000000,45593.000000,45593.000000,45593.000000,45593,45593,45593,45593,45593,45593.000000,45593,45593,45593,45593,45593,45593
unique,45593,1320,23,29,NaN,NaN,NaN,NaN,44,177,193,7,5,NaN,4,4,5,3,4,45
top,0x4607,JAPRES11DEL02,35,4.8,NaN,NaN,NaN,NaN,15-03-2022,NaN,21:30:00,conditions Fog,Low,NaN,Snack,motorcycle,1,No,Metropolitian,(min) 26
freq,1,67,2262,7148,NaN,NaN,NaN,NaN,1192,1731,496,7654,15477,NaN,11533,26435,28159,44469,34093,2123
mean,NaN,NaN,NaN,NaN,17.017729,70.231332,17.465186,70.845702,NaN,NaN,NaN,NaN,NaN,1.023359,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,8.185109,22.883647,7.335122,21.118812,NaN,NaN,NaN,NaN,NaN,0.839065,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,-30.905562,-88.366217,0.010000,0.010000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,12.933284,73.170000,12.988453,73.280000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,18.546947,75.898497,18.633934,76.002574,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,22.728163,78.044095,22.785049,78.107044,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,30.914057,88.433452,31.054057,88.563452,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
import sys
sys.path.append('../src')

In [25]:
from data_cleaning import fix_weather
from data_cleaning import fill_with_mode
from data_cleaning import convert_deliveries_to_int
from data_cleaning import fix_festival
from data_cleaning import fill_numeric_with_mode
from data_cleaning import clean_and_impute_time
from data_cleaning import clean_zero_coordinates_float

In [26]:
# First of all we will fix Weather column 
data=fix_weather(data,'Weatherconditions')

In [27]:
data = fix_festival(data,'Festival')

In [28]:
data=clean_zero_coordinates_float(data)

In [29]:
# Pass as many columns as you need 
data = fill_with_mode(data, 'Road_traffic_density', 'Weatherconditions', 'City')

In [30]:
data=convert_deliveries_to_int(data,'multiple_deliveries')
data.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [31]:
data['multiple_deliveries'].isnull().sum()

np.int64(993)

In [32]:
data = fill_numeric_with_mode(data,'multiple_deliveries')
data = clean_and_impute_time(data,'Time_taken(min)')

In [33]:
data['multiple_deliveries'].isnull().sum()

np.int64(0)

In [34]:
data.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

#### removing ill-logical columns

In [35]:
data = data.drop(columns=['ID','Delivery_person_ID','Delivery_person_Age','Delivery_person_Ratings','Order_Date','Time_Orderd','Time_Order_picked'], errors='ignore')

In [36]:
from Distance_calculation import haversine_distance

In [37]:
coords = [
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude",
]
for col in coords:
    data[col] = data[col].abs()

data["distance_km"] = haversine_distance(
    data["Restaurant_latitude"],
    data["Restaurant_longitude"],
    data["Delivery_location_latitude"],
    data["Delivery_location_longitude"],
)
data["distance_km"]=data["distance_km"].round(2)

In [38]:
data.describe(include='all')

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),distance_km
count,45593.000000,45593.000000,45593.000000,45593.000000,45593,45593,45593.000000,45593,45593,45593.0,45593,45593,45593.000000,45593.000000
unique,NaN,NaN,NaN,NaN,6,4,NaN,4,4,<NA>,2,3,NaN,NaN
top,NaN,NaN,NaN,NaN,Fog,Low,NaN,Snack,motorcycle,<NA>,No,Metropolitian,NaN,NaN
freq,NaN,NaN,NaN,NaN,8270,16078,NaN,11533,26435,<NA>,44697,35293,NaN,NaN
mean,18.882263,76.841732,18.947765,76.909297,NaN,NaN,1.023359,NaN,NaN,0.750225,NaN,NaN,26.294607,10.178287
std,5.245988,3.371615,5.247587,3.370734,NaN,NaN,0.839065,NaN,NaN,0.56743,NaN,NaN,9.383806,5.735535
min,9.957144,72.768726,9.967144,72.778726,NaN,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,10.000000,1.470000
25%,13.029198,73.915367,13.095801,74.006619,NaN,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,19.000000,5.950000
50%,18.554382,75.902847,18.640963,76.011991,NaN,NaN,1.000000,NaN,NaN,1.0,NaN,NaN,26.000000,10.430000
75%,22.732225,78.046106,22.785049,78.107044,NaN,NaN,2.000000,NaN,NaN,1.0,NaN,NaN,32.000000,13.990000
max,30.914057,88.433452,31.054057,88.563452,NaN,NaN,3.000000,NaN,NaN,3.0,NaN,NaN,54.000000,42.830000

In [39]:
data.to_csv(r'../Datasets/Cleaned/Data_cleaned.csv',index=False)